import 'package:json_annotation/json_annotation.dart';

part 'report_archive_model.g.dart';

/// One archived report copy — the record of a report command's output being
/// preserved after a run, instead of being silently overwritten by the next
/// one. See docs/RUN_EXPERIENCE_REDESIGN.md §8.
@JsonSerializable(includeIfNull: false, explicitToJson: true)
class ReportArchive {
  /// The run this report was generated by — matches the id
  /// [RunProvider.start] returns, joinable with [RunRecord.runId].
  final String runId;
  final String projectId;
  final String surfaceId;

  /// Display name of the script that produced this report — kept as plain
  /// text since the script itself may be renamed/deleted later.
  final String script;
  final String environment;

  /// `"android"` | `"ios"` | null (web, or not applicable).
  final String? platform;

  /// Device UDID the run was bound to, if any.
  final String? device;

  /// The fully substituted report command that was actually run — kept so
  /// Regenerate can re-run the exact same command later without re-resolving
  /// the pool.
  final String commandUsed;

  final DateTime generatedAt;

  /// Where the report tool itself wrote its output inside the project repo.
  /// May no longer exist by the time Regenerate is attempted (repo cleaned).
  final String sourcePath;

  /// Where this app copied the output to under app-managed storage — what
  /// Open/Share actually acts on.
  final String archivePath;

  const ReportArchive({
    required this.runId,
    required this.projectId,
    required this.surfaceId,
    required this.script,
    required this.environment,
    this.platform,
    this.device,
    required this.commandUsed,
    required this.generatedAt,
    required this.sourcePath,
    required this.archivePath,
  });

  ReportArchive copyWith({
    DateTime? generatedAt,
    String? archivePath,
  }) =>
      ReportArchive(
        runId: runId,
        projectId: projectId,
        surfaceId: surfaceId,
        script: script,
        environment: environment,
        platform: platform,
        device: device,
        commandUsed: commandUsed,
        generatedAt: generatedAt ?? this.generatedAt,
        sourcePath: sourcePath,
        archivePath: archivePath ?? this.archivePath,
      );

  factory ReportArchive.fromJson(Map<String, dynamic> json) =>
      _$ReportArchiveFromJson(json);

  Map<String, dynamic> toJson() => _$ReportArchiveToJson(this);
}
